### ISSUE TITLE
add support for soundcheck / patching

### ISSUE THREAD

**Issue by pauloponciano1980** [fmalcher/soundcraft-ui#109]
I usually use my UI24r to rehearse with bands here in my studio, and in between I like to listen to what we play. I was able to integrate this package with Alexa through "sinricpro", just missing this soundcheck feature to be perfect

**Comment by fmalcher** [comment]
Alright! Can you please add some more info about which functions exactly should be usable through the library? Tbh, I've never used the soundcheck features before 😅

**Comment by pauloponciano1980** [comment]
The soundcheck function has the objective of directing the channels of the multitrack recording to the pendrive tracks instead of the hardware input. This allows channels to be mixed without the band playing at the same time.
![image](https://user-images.githubusercontent.com/34140373/227097655-40a8b350-d2f9-4efa-b7a2-e076e31ab491.png)

**Comment by fmalcher** [comment]
```
SETD^var.mtk.soundcheck^0
SETD^var.mtk.soundcheck^1
```

**Comment by pauloponciano1980** [comment]
you are fantastic! thanks! I will start the tests
