### ISSUE TITLE
MultiTrack recording not available

### ISSUE THREAD

**Issue by jebbgrenham** [fmalcher/soundcraft-ui#118]
Thanks so much for your work on this library. So far everything has worked "as advertised" until now. Really great library!

When I try to access the multi track recorder via:

`conn.recorderMultiTrack.recordToggle()`

`Property 'recorderMultiTrack' does not exist on type 'SoundcraftUI'.`

TS suggests recorderDualTrack weirdly...

**Comment by jebbgrenham** [comment]
Hmm. Perhaps I've jumped the gun on opening an issue - it seems that my node module source is different than the repo... Soundcraft-ui.ts is missing imports for DeviceInfo and MultiTrackRecorder. Must be out of date somehow.

**Comment by jebbgrenham** [comment]
It seems that for some reason npm served up v0.11.0 as a default. Not sure why. That's an issue - though not an issue with your library :)

**Comment by fmalcher** [comment]
I just installed the package in a project via NPM and got v2.0.1, so it seems to work. I think there's nothing we can do here.
