### ISSUE TITLE
Player track selection documentation

### ISSUE THREAD

**Issue by jebbgrenham** [fmalcher/soundcraft-ui#119]
I've been working with conn.player.loadTrack(track, playlist) in order to overcome soundcraft's weird behaviour when shuffle is on (that the first track in the playlist always plays first before shuffling the rest). I've been trying to call
`conn.player.loadTrack(aRandomWholeNumber, 'Music')`
in order to induce a random track to play, but it still always plays the first track first.

What I'm not sure is if this is by design in your library or not. Am I meant to pass the entire track name/file name to this method? I assumed it was a number, but it's not working as I anticipated. For now I've resolved to this solution, which isn't sane, but it works.
```
conn.player.setShuffle(1)	
conn.player.next() //this will be a shuffled track
conn.player.play()
```

**Comment by fmalcher** [comment]
> Am I meant to pass the entire track name/file name to this method?

Yes! 🙂 This comes from the design of the protocol messages. The mixer expects the full playlist and track name (!), not the index. I added this info in the readme: https://github.com/fmalcher/soundcraft-ui/commit/63bec3ad3186d46b973db9ddf2aca8df09765d77
