### ISSUE TITLE
add ready signal

### ISSUE THREAD

**Issue by fmalcher** [fmalcher/soundcraft-ui#12]
Once all info has been harvested from the mixer, fire a ready event so that consumers know when they can start to consume.
Could be solved by debouncing the messages/state stream

**Comment by fmalcher** [comment]
waiting to continue, until we've found out more about the INIT command and the JSON object that the mixer is supposed to return after INIT. cc @JeffreyDavidsz

**Comment by NaturalDevCR** [comment]
I observe and wait for the OPEN status to start to consume the api...

**Comment by fmalcher** [comment]
That's fine, but it will sitll take a few seconds after this until the full state has been received from the mixer.
I don't think we need this feature at the moment, though. That's why the issue is still open.
