### ISSUE TITLE
Si Expression Consoles Support

### ISSUE THREAD

**Issue by elvisveiga** [fmalcher/soundcraft-ui#122]
Hey! Congratulations on the library! 
Do you also intend to support Si Expression consoles?

Thank you.

**Comment by fmalcher** [comment]
> Do you also intend to support Si Expression consoles?

No, unfortunately. The protocols are completely different (Si Expression uses the HiQnet protocol), so it wouldn't make sense to integrate both into the same library. I have never worked with HiQnet devices and I'm not planning to build a library around HiQnet. Maybe there is one already?
