### ISSUE TITLE
Authenticate question

### ISSUE THREAD

**Issue by amorimcode** [fmalcher/soundcraft-ui#129]
It's possible to connect to connect to soundcraft ui via APP? I wish to add an option in my React-Native app to auto login on soundcraft

**Comment by fmalcher** [comment]
Thanks for your question! This is a very generic JavaScript/TypeScript library, so you can use it in whatever environment you want. I'm actively using the lib in Node.js and Angular (browser).
I have never tried React Native, but as long as you can run JS code and open WebSocket connections, it should work.

**Comment by amorimcode** [comment]
thanks! i gonna try
