### ISSUE TITLE
Change FX parameters

### ISSUE THREAD

**Issue by yleguern64** [fmalcher/soundcraft-ui#140]
We could easily send values to change part of effects.

Do you think its possible to create this new feature ? (no urgence)

```
3:::SETD^f.0.par1^0.4867674858223062	36	
3:::SETD^f.0.par2^0.4848771266540643	36	
3:::SETD^f.0.par3^0.998109640831758		35	
3:::SETD^f.0.par4^0.996219281663516		35	
3:::SETD^f.0.par4^0.9924385633270322	36	
3:::SETD^f.0.par4^0.9905482041587902	36	
3:::SETD^f.0.par4^0.9886578449905482	36	
3:::SETD^f.0.par4^0.9867674858223062	36	
3:::SETD^f.0.par4^0.9848771266540642	36	
3:::SETD^f.0.par4^0.9829867674858223	36	
3:::SETD^f.0.par4^0.9810964083175804	36	
3:::SETD^f.0.par4^0.9792060491493384	36	
3:::SETD^f.0.par4^0.9773156899810964	36	
3:::SETD^f.0.par5^0.001890359168241966	38	
3:::SETD^f.0.par5^0.005671077504725898	38	
3:::SETD^f.0.par5^0.00945179584120983	37	
3:::SETD^f.0.par5^0.013232514177693762	38	
3:::SETD^f.0.par5^0.015122873345935728	38	
3:::SETD^f.0.par5^0.017013232514177693	38	
3:::SETD^f.0.par5^0.01890359168241966	37	
3:::SETD^f.0.par5^0.020793950850661626	38	
3:::SETD^f.0.par5^0.022684310018903593	38	
3:::SETD^f.0.par5^0.024574669187145556	38
```

**Comment by fmalcher** [comment]
Unfortunately, this is not as easy as it seems. Sending and receiving the messages is trivial, but we also need a proper API surface for this. Each effect has a slightly different interpretation of the 6 params:

![Screenshot 2024-09-09 at 11 41 57](https://github.com/user-attachments/assets/fbaf0c9f-72d6-414b-bbfb-619e8622b617)
![Screenshot 2024-09-09 at 11 42 37](https://github.com/user-attachments/assets/c52e3728-4271-4add-b7ec-fb59f16a4244)
![Screenshot 2024-09-09 at 11 42 33](https://github.com/user-attachments/assets/a0eeea8d-b6cc-434b-ac65-071ea9b07902)

This means, for each effect type we have to create a different class/object with well-named properties and methods. Each value has to be transformed into a human-readable value like in the UI (`ms`, `%`, `kHz`, etc.). 

What could make things worse is that the different mixer models could have different effects.

So, to make this properly (and not just fast), we first need an idea of the API surface, then collect all infos we want to exchange and finally, create mappings from linear values to output values.

**Comment by fmalcher** [comment]
FX types (Ui24R):

-1: inactive / none
0: Reverb
1: Delay
2: Chorus
3: Room

```
SETD^f.3.fxtype^1
```

**Comment by fmalcher** [comment]
The foundation for this was set in #149 .
Since the FX type can change at runtime, I think it is almost impossible to create a real specific API for this.
Therefore, I will stick with your suggestion and allow to generically change the six FX params.
First draft:

```ts
// get stream of values for FX param 1 on FX 1
conn.fx(1).getParam(1).subscribe(v => /* ... */);

// set FX param 4 on FX 2
conn.fx(2).setParam(4, 0.75);
```
