### ISSUE TITLE
Change WebSocket abstraction

### ISSUE THREAD

**Issue by fmalcher** [fmalcher/soundcraft-ui#154]
At the moment, this lib uses the `isomorphic-ws` package to build an abstraction around WebSocket. This is because the browser and Node.js use different objects for this.
For some reason, we see problems around this from time to time, e.g. https://github.com/fmalcher/soundcraft-ui/issues/153

An idea is to remove the abstractions and let the users of this library decide which WebSocket object they want to use.
On the one hand, this makes it a bit more difficult to use the library, on the other hand there is less magic happening under the hood. For special environments, this will give users full control over the WebSocket object, and the library will not have to handle each and every special use-case.

`WebSocket` could be the default object there, e.g. like this:

```
// browser
new SoundcraftUi(ip)

// browser
new SoundcraftUi(ip, WebSocket)

// Node.js
const ws = require('ws');
new SoundcraftUi(ip, ws);
```

```
export class SoundcraftUi {
  constructor(targetIp: string, wsCtor?: any) {
    // ...
    // apply default
    if (!wsCtor && typeof WebSocket !== 'undefined') {
      wsCtor = WebSocket;
    }
  }
}
```

**Comment by NaturalDevCR** [comment]
What about this package instead?

https://github.com/JoCat/modern-isomorphic-ws

<img width="1170" alt="image" src="https://github.com/user-attachments/assets/64aad4b9-a6c2-42e2-923a-da48fa9ac996">

Not sure if this would be an improvement over the original one, and I had to mention it seems less known in comparission.

But still isomophic-ws has some years without activity anyway.

**Comment by fmalcher** [comment]
Let's give it a try!I don't think this will solve the problem you had in #153, but `modern-isomorphic-ws` looks a bit cleaner.
I also made it possible to configure the WebSocket constructor at initialization. I will try and see whether this solves your problem.

**Comment by fmalcher** [comment]
Yay! The other package seems to have solved the problem in your project 🥳 
I have no idea why because the two packages do basically the same – but it works!

However, I will keep the option to provide an individual WebSocket constructor, just in case.

**Comment by fmalcher** [comment]
Well … the downside is that it doesn't seem to work in Node.js anymore 😬
