### ISSUE TITLE
[question] how to monitor/track every action made on UI ?

### ISSUE THREAD

**Issue by apcloic** [fmalcher/soundcraft-ui#55]
Hi,

For an experimental project, I need to record/track every action made on UI such as volume change, FX, etc. and save all as json or XML.
Does this connection library allow me to do this ? 
Regards,

**Comment by fmalcher** [comment]
Yes and no! I added a stream in the `MixerStore` class that lets you receive all relevant raw messages. (Relevant means, this only contains messages of type `SETD` and `SETS` but not `RTA` or any other).

I added a section further down in the README which explains this. With release 0.9.0 you can receive messages as follows:

```ts
conn.store.messages$.subscribe(msg => {
  // handle message
});
```

Please be aware of a few things:
- After successful connection. the mixer pushes its full state as single messages. You will have a huge message burst which could make your browser freeze a bit.
- Those messages only reflect the global mixer state which is NOT every single action in the UI. All local actions that only affect the UI but not the mixer state will not be visible here.

I will release 0.9.0 soonish. Hope this helps!

**Comment by apcloic** [comment]
@fmalcher thanks a lot for detailed explanation.
