### ISSUE TITLE
MasterPassword

### ISSUE THREAD

**Issue by NaturalDevCR** [fmalcher/soundcraft-ui#77]
Hi, first than all, thanks a lot for this library, I'm wondering how did you figure out the raw messages you could send to the mixer, and the process to get this to work... 

I am amazed how the master password means no barrier at all for the library to modify parameters, I mean you could literally go to a venue, figure the IP used by the mixer, and screw everything up by sending parameters through this library, lol!, this is insane...

I'm really wondering what was the purpose of this library... I mean, now I want to create my own User interface with this library on top, or at least extend the mixer itself with some shortcuts...

It would be awesome to have the mixer firmware publicly released but I guess that's not gonna happen ever. 

Thanks in advance!

**Comment by fmalcher** [comment]
> I'm wondering how did you figure out the raw messages you could send to the mixer, and the process to get this to work...

Mostly reverse engineering! You can explore the WebSocket messages in the browser DevTools. You can also enter `enableDebug()` into the browser console and the mixer will output the raw messages.

> I'm really wondering what was the purpose of this library... I mean, now I want to create my own User interface with this library on top, or at least extend the mixer itself with some shortcuts...

That was the exact purpose 😄 I developed this library to integrate the Soundcraft Ui mixers into Bitfocus Companion for studio automation, see here: https://github.com/bitfocus/companion-module-soundcraft-ui
I didn't want to couple the mixer communication to the companion module so I made it a separate lib.
So yes please, build your own automations, shortcuts and custom UI – that's what I made this for! 🙂
