### ISSUE TITLE
Select Channel programatically

### ISSUE THREAD

**Issue by NaturalDevCR** [fmalcher/soundcraft-ui#94]
Hi, I've just seen in a MIDI app that it's possible to select a channel in the Ui programatically...

I've been looking around how to do this in the WS messages... and I found something, it's not perfect but it's a start:

`BMSG^SYNC^CDB^3`

This message is sent when you click on a channel on this section:

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/35145882/209887574-ce6a5495-c4a6-4cdc-a2fa-11ecaf0bca46.png">

But this message is sent only if the SYNC option is turned on in the mixer... so the message composes as follows:

BMSG => ?
SYNC => The SYNC option which has to be activated.
CDB => The SYNC_ID (CDB is my own)
3 => The channel number.

This might be a start to look around to programatically select a channel...

**Comment by fmalcher** [comment]
What is the use case for this?

**Comment by NaturalDevCR** [comment]
It would make possible to assign a MIDI knob or fader to be applied to any channel fader for example with the same fader from the midi controller.

I know this very specific, and I understand if you prefer to pass on it... So I'll close the issue, thanks in advance
