### ISSUE TITLE
Set and Get gain won't work in Ui12 and Ui16

### ISSUE THREAD

**Issue by NaturalDevCR** [fmalcher/soundcraft-ui#96]
The RAW message in the Ui12 and Ui16 seems to be

`SETD^i.0.gain^0`

Which is different in the case of the Ui24 where you can patch inputs to different channels.

**Comment by NaturalDevCR** [comment]
The same applies when subscribing to gain$ or gainDB$,

Thanks in advance!

**Comment by fmalcher** [comment]
@NaturalDevCR  Do you have a Ui12 available for testing? Can you confirm that the gain messages are the same as for the Ui16? Is the gain range also -40...50 dB?

**Comment by gaborveszpremi** [comment]
@fmalcher I have an U12 and I am working on it. On the web interface of the Ui12, the gain goes from -40dB to +50dB.
If I subscribe to "gainDB" (that can be done with your code now, with 3 line changes in hw-channel.js and state-selectors.js and it really works with Ui12), your code sends me values from -6 to 57.
I think this calculation is made by your code, so, the answer is: Yes, the Ui12 originally sets gain from -40 to 50dB

**Comment by fmalcher** [comment]
@gaborveszpremi Thank you so much! Then there's everything clear to me. A PR will land soon. 🙂

**Comment by fmalcher** [comment]
I released v1.3.0 yesterday with this feature included. It was more than a fix, actually. Thanks for reporting!
If anybody has time to confirm things are working correctly, I'm happy about feedback.

**Comment by gaborveszpremi** [comment]
Hi! It works perfectly with my Ui12.
I upgraded to v1.3.0 and I tested all the listeners (gain$, gainDB$, phantom$) and all the set... change... toggle.... etc functions of HwChannels that are documented in README.md, and I found all of them working fine. Also, gain Db values are in sync with the web UI of the device. Thanks for your great work!
